version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
        - ./data/postgres:/var/lib/postgresql/data
        - ./scripts/:/docker-entrypoint-initdb.d/
    ports:
        - "5432:5432"
    environment:
        POSTGRES_PASSWORD: mysupersecret
  confluence:
    container_name: confluence
    image: atlassian/confluence
    volumes:
      - ./data/confluence:/var/atlassian/application-data/confluence
    ports:
      - "8090:8090"
      - "8091:8091"
    environment:
        ATL_JDBC_URL: "jdbc:postgresql://postgres:5432/confluence"
        ATL_JDBC_USER: "postgres"
        ATL_JDBC_PASSWORD: "mysupersecret"
        ATL_DB_TYPE: "postgresql"
    depends_on:
        - postgres
